### ISSUE TITLE
Homebridge doesnt start

### ISSUE THREAD

**Issue by flonatural** [normen/homebridge-landroid#16]
hello, 
first at all I want to say thanks for this Plugin and now i talk about my issue :)

After installing ur Plugin on Hoobs 3 it doesnt start up anymore.

The Log said just that I'm connected to the Cloud but nothing more. Have I to type anything in the Configured Mowers field? because it araise always my stuff if I type in the name. 

Thanks for ur help

**Comment by normen** [comment]
I don't know what you're talking about at all.
