### ISSUE TITLE
Try to send a message but could not find the mower / Error: Mower has not been configured yet.

### ISSUE THREAD

**Issue by nicoh88** [normen/homebridge-landroid#17]
Hi Normen,

mit großer Interesse habe ich mir das Issue #12 durchgelesen. Leider konnte ich mein Problem nicht lösen.

```
npm list --depth=0 -g | grep -i landroid
├── homebridge-landroid@0.6.6
```

```
cat /var/lib/homebridge4/config.json
...
  "platforms": [
    {
      "platform": "Landroid",
      "email": "YYY",
      "pwd": "XXX",
      "debug": true,
      "landroids": [
        {
          "name": "Mähroboter",
          "dev_name": "0"
        }
      ]
    },
...
```

```
Apr 09 16:13:45 frida homebridge[15545]: [2020-4-9 16:13:45] [Landroid] Connected to WORX cloud.
Apr 09 16:13:46 frida homebridge[15545]: [2020-4-9 16:13:46] [Landroid] [DEBUG] MOWER: {"id":3285XX,"product_id":49,"user_id":1933XX,"serial_number":"20193019840102157XXX","mac_address":"98D86331XXXX","name":"WR141E","locked":true,"firmware_version":3.07,"firmware_auto_upgrade":false,"push_notifications":true,"sim":null,"push_notifications_level":"notice","test":0,"iot_registered":true,"pin_code":"1337","registered_at":"2019-05-21 00:00:00","online":true,"app_settings":null,"accessories":null,"features":{"unrestricted_mowing_time":true,"multi_zone":true,"wifi_connection":"smartlink_tube_display","display_type":"tube","lock":true,"pin":true,"rain_delay":true,"chassis":"m_2019","mqtt":true,"provisionable":true,"wifi_pairing":"smartlink","tracking_firmware":true,"provisoning_replaceable":true},"pending_radio_link_validation":null,"mqtt_topics":{"command_in":"PRM100/98D86331XXXX/commandIn","command_out":"PRM100/98D86331XXXX/commandOut"},"warranty_registered":true,"purchased_at":"2019-05-19 00:00:00","warranty_expires_at":"2022-05-19 00:00:00","setup_location":{"latitude":50.192902,"longitude":11.80366},"city":{"id":2867XXX,"country_id":276,"name":"Munchberg","latitude":50.200001,"longitude":11.78333,"created_at":"2018-02-15 22:22:52","updated_at":"2018-02-15 22:22:52"},"time_zone":"Europe/Berlin","lawn_size":300,"lawn_perimeter":null,"auto_schedule_settings":null,"auto_schedule":false,"distance_covered":379795,"mower_work_time":22538,"blade_work_time":21734,"blade_work_time_reset":20668,"blade_work_time_reset_at":null,"battery_charge_cycles":116,"battery_charge_cycles_reset":110,"battery_charge_cycles_reset_at":null,"messages_in":437,"messages_out":23383,"raw_messages_in":38252,"raw_messages_out":23383,"created_at":"2019-02-27 01:04:46","updated_at":"2020-04-09 13:51:20"}
Apr 09 16:14:03 frida homebridge[15545]: [2020-4-9 16:14:03] [Landroid] Error: Mower has not been configured yet.
Apr 09 16:14:03 frida homebridge[15545]: [2020-4-9 16:14:03] [Landroid] Sending to landroid cloud: [{"cmd":1}] (#null)
Apr 09 16:14:03 frida homebridge[15545]: [2020-4-9 16:14:03] [Landroid] Try to send a message but could not find the mower
Apr 09 16:14:06 frida homebridge[15545]: [2020-4-9 16:14:06] [Landroid] Error: Mower has not been configured yet.
Apr 09 16:14:06 frida homebridge[15545]: [2020-4-9 16:14:06] [Landroid] Sending to landroid cloud: [{"cmd":3}] (#null)
Apr 09 16:14:06 frida homebridge[15545]: [2020-4-9 16:14:06] [Landroid] Try to send a message but could not find the mower
```

---

Was mir auffällt ist, dass `[Landroid] [DEBUG] DATA: ` wie beim #12 komplett fehlt.

Habe `dev_name` 0, 1 und 2 durchprobiert, des Weiteren `name` auch mit WR141E versucht - ohne Erfolg.

---

Irgendwas scheint hier faul zu sein... die DeskApp macht Probleme und die Landroid-Bridge auch. 👎 STRANGE! Die iOS-App funktioniert.

---

UPDATE: Scheinbar funktioniert auch nur die Status-Abfrage über die iOS-App - "nach Hause" kann ich ihn nicht schicken. Daten werden ca. alle 10 Minuten aktualisiert. (egal ob WLAN oder LTE)

Gruß Nico

**Comment by normen** [comment]
Jo, "dev_name" wäre dann eig. `WR141E` bei dir.

Kein' plan was da sonst schief läuft, hast vielleicht in deinem router die sicherheitseinstellungen auf "paranoid" stehen oder so?

**Comment by nicoh88** [comment]
> Jo, "dev_name" wäre dann eig. `WR141E` bei dir.

Ok. Seit heute Morgen bekomme ich auch den DATA DEBUG in der Log angezeigt und die iOS App aktualisiert auch ordentlich, inkl. Zeitstempel, beim „Pull-Down“. Ebenso die DeskApp.

`Apr 10 10:44:41 frida homebridge[585]: [2020-4-10 10:44:41] [Landroid] [DEBUG] DATA: {"cfg":{"id":1,"lg":"it","tm":"10:44:39","dt":"10/04/2020","sc":{"m":1,"p":-100,"d":[["09:15",645,1],["09:30",300,1],["09:30",300,0],["09:30",300,0],["09:30",300,1],["09:30",300,0],["14:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":180,"sn":"2019301984010215XXXX"},"dat":{"mac":"98D86331XXXX","fw":3.07,"bt":{"t":9.9,"v":19.12,"p":100,"nr":119,"c":0,"m":0},"dmp":[0.1,-5.6,14.7],"st":{"b":22298,"d":389575,"wt":23122,"bl":114},"ls":1,"le":0,"lz":0,"rsi":-47,"lk":1,"act":1,"tr":0,"conn":"wifi"}}`

Dennoch kann ich den Mähroboter über HomeKit nicht starten. Kommt weiterhin die Meldung. Habe 0, 1 und 2 durchprobiert.

Ziehe mir nachher mal ein Fork und teste etwas. Melde mich.

> Kein' plan was da sonst schief läuft, hast vielleicht in deinem router die sicherheitseinstellungen auf "paranoid" stehen oder so?

Nope - normale Fritzbox. Keine großen Sicherheitseinstellungen.

**Comment by nicoh88** [comment]
> Jo, "dev_name" wäre dann eig. `WR141E` bei dir.

🤦 Natürlich - ich Vollpfosten. Läuft.

```
    {
      "platform": "Landroid",
      "email": "xyz",
      "pwd": "password",
      "debug": true,
      "landroids": [
        {
          "name": "Mähroboter",
          "dev_name": "WR141E"
        }
      ]
    }
```

Schöne Ostern!
Gesund bleiben!

Gruß Nico
