### ISSUE TITLE
Can`t find dev_name

### ISSUE THREAD

**Issue by fabiovit** [normen/homebridge-landroid#19]
Hello,
how is it possible to find dev_name?
I get this error:
[Homebridge] [4/14/2020, 1:31:31 PM] [Landroid] Error: Mower has not been configured yet.
[Homebridge] [4/14/2020, 1:31:31 PM] [Landroid] Sending to landroid cloud: [{"cmd":1}] (#null)
[Homebridge] [4/14/2020, 1:31:31 PM] [Landroid] Try to send a message but could not find the mower

        {
            "platform": "Landroid",
            "email": "xxx@gmail.com",
            "pwd": "xxxx",
            "landroids": [
                {
                    "name": "Tagliaerba",
                    "dev_name": "1"
                }
            ]
        }

**Comment by normen** [comment]
Earlier in the log.

**Comment by JangoBritt** [comment]
Also, in the Landroid app, it’s what it shows after the “Landroid “

Eg: “Landroid Bowser” = “Bowser”

**Comment by Schosch83** [comment]
Hello, me the same before in the log only:
[2020-4-15 21:59:32] [Landroid] Initializing Landroid platform...
[2020-4-15 21:59:32] [Landroid] Initializing platform accessory 'Thomas'...
[2020-4-15 21:59:36] [Landroid] Connected to WORX cloud.
[2020-4-15 21:59:38] [Landroid] Found mower in Worx Cloud with name: Thomas

Then I try to start the Mower in Home.
The log:
[2020-4-15 22:13:55] [Landroid] Error: Mower has not been configured yet.
[2020-4-15 22:13:55] [Landroid] Sending to landroid cloud: [{"cmd":1}] (#null)
[2020-4-15 22:13:55] [Landroid] Try to send a message but could not find the mower

Also no status and Battery showing.

**Comment by normen** [comment]
"Thomas" is the dev_name.

> [2020-4-15 21:59:38] [Landroid] Found mower in Worx Cloud with name: Thomas

**Comment by Schosch83** [comment]
Yes that‘s the Mower Name!
You Need a Debug?

**Comment by normen** [comment]
This should be your config:
```
    {
        "platform": "Landroid",
        "email": "xxx",
        "pwd": "xxx",
        "landroids": [
            {
                "name": "Thomas",
                "dev_name": "Thomas"
            }
        ]
    }
```

**Comment by Schosch83** [comment]
Okay I change the dev_name from 1 to Thomas and his Works.
Thank you 👍

**Comment by normen** [comment]
The latest version 0.7.0 detects all mowers automatically, no more names to be entered
