### ISSUE TITLE
Feature suggestion: charging status

### ISSUE THREAD

**Issue by andy-dinger** [normen/homebridge-landroid#21]
Would it be possible to create an accessory to show the current charging status? This is in addition to the current battery %

**Comment by normen** [comment]
Like a switch or another contact sensor or something? Nah, thats ugly 😉 The charging status is reported to HomeKit already anyway. If you want to see it in Apples Home App you could make a dummy switch and then assign an automation based on the charging state in an app that supports more HomeKit functions, like Elgatos Eve app.
