### ISSUE TITLE
no Update from the Cloud

### ISSUE THREAD

**Issue by tobihoby** [normen/homebridge-landroid#22]
Hi,

in the Log i found these:
        Line 102: 2.5.2020, 14:15:46 - Loaded plugin "homebridge-landroid".
	Line 126: 2.5.2020, 14:15:47 - [Landroid] Initializing Landroid platform...
	Line 265: 2.5.2020, 14:15:47 - [Landroid] DidFinishLaunching
	Line 281: 2.5.2020, 14:15:49 - [Landroid] Connected to WORX cloud.
	Line 304: 2.5.2020, 14:15:52 - [Landroid] Found Landroid in Worx Cloud with name: M500
	Line 305: 2.5.2020, 14:15:52 - [Landroid] Adding Landroid M500 to HomeKit

but no updates from the cloud about status from my landroid...

Greets
Tobi

**Comment by normen** [comment]
Do you get updates in the app?

**Comment by tobihoby** [comment]
the installed plugin landroid version is 0.7.3

**Comment by tobihoby** [comment]
I updated to 0.7.3 manually, since only the latest version 0.7.2 is available under Hoobs

![image](https://user-images.githubusercontent.com/60090762/80868617-29112e00-8c9c-11ea-987f-54248252d5f6.png)

**Comment by normen** [comment]
Do you get updates in the Landroid app? I guess your mower simply isn't working at all.

**Comment by tobihoby** [comment]
yes, the App works fine and is always up to date

**Comment by normen** [comment]
Dunno, maybe Worx is limiting the updates for MQTT clients that are not their own app? Does it update when you open the app? I had that sometimes - homekit wouldn't update, I open the app and homekit updates too.

**Comment by tobihoby** [comment]
It worked without problems so far ... The app updates itself immediately. I reset the app and registered again. No update in the plugin. Apart from the actions mentioned above, the plugin seems to refuse any synchronization.

**Comment by normen** [comment]
Did you maybe add a firewall to your homebridge instance or something? The funny thing is that apprently your mower is found, so there is somewhat of a connection. Maybe you changed the name of your mower? Did you try readding it with the config option?

**Comment by tobihoby** [comment]
No, I haven't changed anything, nor firewall's name of the mower. I have also tried to have the mower read out again, and it worked without any problems. Everything really works, only that no status updates are retrieved from the Worx Cloud.

**Comment by normen** [comment]
What is written in the log when you try to control the mower? There should be a serial appearing as well.

**Comment by tobihoby** [comment]
I reset the homebridge and imported an older backup. It works again now. I'm waiting for the update to version 0.7.3.

**Comment by normen** [comment]
Really, if you don't want to help fixing the issue then don't post here. This is not a support forum. And definitely not for hoobs bugs.

**Comment by tobihoby** [comment]
I can't say where the error is, what else can I do?

**Comment by normen** [comment]
Maybe you didn't realize but I asked two questions the lasts posts that you basically ignored. But anyway this isn't very fruitful if theres no errors and no nothing.

**Comment by tobihoby** [comment]
Nothing else is shown in the log, no matter what I do, only the above-mentioned entries can be found in the log, sorry that it was not so clearly written.

**Comment by normen** [comment]
If theres no message when you control the mower at all then HomeKit doesn't even send any switch data to the plugin, hinting at an issue outside of the plugin.

**Comment by andy-dinger** [comment]
> Dunno, maybe Worx is limiting the updates for MQTT clients that are not their own app? Does it update when you open the app? I had that sometimes - homekit wouldn't update, I open the app and homekit updates too.

Yes, I now seem to have that same problem since I updated to Homebridge 1.0. Did you find anything that helped to fix it?

**Comment by tobihoby** [comment]
I have not made any further discoveries so far
