### ISSUE TITLE
https Verbindung 

### ISSUE THREAD

**Issue by fighterzg6** [normen/homebridge-landroid#29]
Hallo, bekomme seit heute diese Fehlermeldung:

[2021-4-13 8:21:20] [homebridge-landroid] Connected to WORX cloud.
[2021-4-13 8:21:20] [homebridge-landroid] StatusCodeError: 426 - "This service requires use of the HTTPS protocol."
    at new StatusCodeError (/usr/local/lib/node_modules/homebridge-landroid/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-landroid/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-landroid/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-landroid/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-landroid/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-landroid/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  statusCode: 426,
  error: 'This service requires use of the HTTPS protocol.',
  options: {
    method: 'GET',
    uri: 'http://api.worxlandroid.com/api/v2/users/me',
    headers: {
      'Content-Type': 'application/json',
      Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWQ4MjFhMmRjMTYyYjUwYThmYTI4Yjc4YTY1OTEzZjU5Mjc5NDA5N2E3YjlhZTM5MWE0MjY1MDNlMjVkZTMxYjkyMzI0YmNlNTQ3N2UxMmUiLCJpYXQiOjE2MTgyOTQ4ODAsIm5iZiI6MTYxODI5NDg4MCwiZXhwIjoxNjQ5ODMwODgwLCJzdWIiOiIzNTA0NzQiLCJzY29wZXMiOlsiKiJdfQ.X6RlkKFsMSzt1nvamakp-AXRcRhspIq9iMfJcz3IZX_LjP_tyy8hobmNcc4U-fjp0nCuiRPk8qUhwM6FrOdx2maK5-JcPyJACdw-PblUfSVsIeeFtB89QY8l9KdFaxm6mr99sMrsUQLARDBpI9IKwJYQzz-w6NgpQih4s-vmHKHe2WUWeRXNRQwVvRB6x1aCrRnj10xGczlReaLa2EeKZgdxQAhbp3YavDuXBkePhl-YD-gfVvIQDl5FmNw72xS4dj8yHgJfAVm0-KUTyUuchgUS95hRvuS3BjcmGUl3bi57e6tgBQCj5Pptg43Uq08jJn3ByH1Hyg1MbRnj8PlhIE2WV6ArwE5J7Go66rVoyBVTXtHxTPGHDmG3EwZg-eWSuUTr0hKpdMd_IHQ3Xk4pQbgoPrNAGQwxIns7tw11eWStI45YbvzkPOPK7dW9KnlaqrNPCdsl6PD7qzNuYMKfVaCzNnsiVXPiw4j8hiUAtA516ot22Argsl6Vheu4zNfrqlphiz4suYcskS85sbf24fWyhFfBEm9FJSvODMeaRuacYFfuFFLuBJLHhZom0HuhQhca_iuUuIVG1_LwJ-nMwKVKIuW5hClCRRIrjbltPW4tNG88rsooBmjEIYLw2-FaNueKpa9RZYDipREwTvJTMVvZ0k9TWFYEHSYrKHzbjQM'
    },
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    readable: false,
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function],
      error: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.worxlandroid.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(asyncId)]: 66,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.worxlandroid.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(asyncId)]: 66,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      server: 'awselb/2.0',
      date: 'Tue, 13 Apr 2021 06:21:20 GMT',
      'content-type': 'text/plain; charset=utf-8',
      'content-length': '48',
      connection: 'close'
    },
    rawHeaders: [
      'Server',
      'awselb/2.0',
      'Date',
      'Tue, 13 Apr 2021 06:21:20 GMT',
      'Content-Type',
      'text/plain; charset=utf-8',
      'Content-Length',
      '48',
      'Connection',
      'close'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 426,
    statusMessage: '',
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.worxlandroid.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(asyncId)]: 66,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'GET /api/v2/users/me HTTP/1.1\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWQ4MjFhMmRjMTYyYjUwYThmYTI4Yjc4YTY1OTEzZjU5Mjc5NDA5N2E3YjlhZTM5MWE0MjY1MDNlMjVkZTMxYjkyMzI0YmNlNTQ3N2UxMmUiLCJpYXQiOjE2MTgyOTQ4ODAsIm5iZiI6MTYxODI5NDg4MCwiZXhwIjoxNjQ5ODMwODgwLCJzdWIiOiIzNTA0NzQiLCJzY29wZXMiOlsiKiJdfQ.X6RlkKFsMSzt1nvamakp-AXRcRhspIq9iMfJcz3IZX_LjP_tyy8hobmNcc4U-fjp0nCuiRPk8qUhwM6FrOdx2maK5-JcPyJACdw-PblUfSVsIeeFtB89QY8l9KdFaxm6mr99sMrsUQLARDBpI9IKwJYQzz-w6NgpQih4s-vmHKHe2WUWeRXNRQwVvRB6x1aCrRnj10xGczlReaLa2EeKZgdxQAhbp3YavDuXBkePhl-YD-gfVvIQDl5FmNw72xS4dj8yHgJfAVm0-KUTyUuchgUS95hRvuS3BjcmGUl3bi57e6tgBQCj5Pptg43Uq08jJn3ByH1Hyg1MbRnj8PlhIE2WV6ArwE5J7Go66rVoyBVTXtHxTPGHDmG3EwZg-eWSuUTr0hKpdMd_IHQ3Xk4pQbgoPrNAGQwxIns7tw11eWStI45YbvzkPOPK7dW9KnlaqrNPCdsl6PD7qzNuYMKfVaCzNnsiVXPiw4j8hiUAtA516ot22Argsl6Vheu4zNfrqlphiz4suYcskS85sbf24fWyhFfBEm9FJSvODMeaRuacYFfuFFLuBJLHhZom0HuhQhca_iuUuIVG1_LwJ-nMwKVKIuW5hClCRRIrjbltPW4tNG88rsooBmjEIYLw2-FaNueKpa9RZYDipREwTvJTMVvZ0k9TWFYEHSYrKHzbjQM\r\n' +
        'host: api.worxlandroid.com\r\n' +
        'accept: application/json\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/api/v2/users/me',
      _ended: true,
      res: [Circular],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.worxlandroid.com',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      method: 'GET',
      uri: [Url],
      headers: [Object],
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function],
      _rp_reject: [Function],
      _rp_promise: [Promise [Object]],
      _rp_callbackOrig: undefined,
      callback: [Function],
      _rp_options: [Object],
      setHeader: [Function],
      hasHeader: [Function],
      getHeader: [Function],
      removeHeader: [Function],
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      proxy: null,
      tunnel: false,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: 80,
      host: 'api.worxlandroid.com',
      path: '/api/v2/users/me',
      _json: true,
      httpModule: [Object],
      agentClass: [Function],
      agent: [Agent],
      _started: true,
      href: 'http://api.worxlandroid.com/api/v2/users/me',
      req: [ClientRequest],
      ntick: true,
      response: [Circular],
      originalHost: 'api.worxlandroid.com',
      originalHostHeaderName: 'host',
      responseContent: [Circular],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: 'This service requires use of the HTTPS protocol.',
    [Symbol(kCapture)]: false
  }
}

**Comment by normen** [comment]
Thanks, should be fixed in 0.9.2
