### ISSUE TITLE
Edge Cut

### ISSUE THREAD

**Issue by JangoBritt** [normen/homebridge-landroid#3]
Hey, this plugin has made my day! Thanks!

Works perfectly as advertised.

I was wondering if there was any mechanism by which you could trigger an Edge Cut, rather than just starting & stopping? Does that exist in the API you're using? Or is it just a case of switch ON then OFF, to trigger the return home?

It's a shame that the Landroid reports as OFF, rather than "Turning Off" or something like that when it's returning to dock, but I guess that's an API/Accessory type limitation.

Hopefully at some point, Apple will add a Vacuum/Lawnmower/Robot accessory type soon, fingers crossed for WWDC!

**Comment by normen** [comment]
Nah, anything like that would be too much of a hack. It will automatically cut the edge on the set „edge cut days“ in the Landroid app though, even if you manually start it.
