### ISSUE TITLE
Leak sensor not shown and MQTT Error

### ISSUE THREAD

**Issue by Marcusg562** [normen/homebridge-landroid#32]
Hi all,

I've today seen the issue with the Landroid App: 
`[15/06/2021, 02:47:06] [Landroid] MQTT ERROR: Error: getaddrinfo EAI_AGAIN a1optpg91s0ydf-ats.iot.eu-west-1.amazonaws.com`

In Addition to that I don't get the Rain Sensor shown (it is enabled in the Landroid Plugin):
![image](https://user-images.githubusercontent.com/105149/122056580-0384ac80-cdea-11eb-9146-7f4efa764fea.png)

System Information:
Homebridge: v1.3.4
homebridge-landroid: v0.9.3

Best regards
Marcus

**Comment by normen** [comment]
Thats a network connection error (i.e. could be anything from your wifi to your ISP). For the rain sensor you have to reload the mowers so they are newly registered as a device with leak sensor.
