### ISSUE TITLE
Party Mode as extra switch

### ISSUE THREAD

**Issue by slayerofmadness** [normen/homebridge-landroid#33]
Maybe its Possible to add Party Mode as a extra switch, so it could be combined with a automation in home. Thank you :)

**Comment by normen** [comment]
What is party mode? My lawnmower doesn't have such a thing.

**Comment by slayerofmadness** [comment]
i quote worx:
Party mode *
Why do you have a lawn if you don't use it for partying and barbecuing? Right, we see it the same way. Simply activate the "party mode" and the Landroid will suspend its schedule until you deactivate the mode again. Please remember, otherwise the Landroid will not resume its regular routine!

Available for selected models (WR130E, WR139E, WR140, WR140E, WR141E, WR142E, WR143E, WR165, WR165E, WR167E, WR148E, WR147E, WR147E.1, WR150, WR150E, WR153E, WR155, WR155E) and only for lawnmowers with firmware- Version 3.16 and higher.

:)

**Comment by normen** [comment]
As said I don't have Party Mode in my mower so I can't test it but v0.9.4 theoretically has support for that now. You have to enable the new switch in the plugins "advanced" settings.

Edit: Thats v0.9.5 now, fixed a probable issue

**Comment by slayerofmadness** [comment]
Sorry, my bad, didn't get it the first time. Thank you for your extra fast work. Thats really great.

ATM i don't see the Party Switch, will test again tomorrow :)

Schönen Abend / Nacht dir :)

**Comment by slacky84** [comment]
Hi @normen - firstly thanks for your efforts in developing this plugin!
Despite enabling the Party Mode in advanced settings, I too do not see the switch appear under Accessories.

**Comment by normen** [comment]
Try reloading the mowers

**Comment by slayerofmadness** [comment]
Thank you, this worked perfectly!

Great job :) !!!

**Comment by normen** [comment]
Cool, thanks for the feedback.
