### ISSUE TITLE
Possible? Battery status display in Home App

### ISSUE THREAD

**Issue by luissimoes** [normen/homebridge-landroid#35]
In the homebridge accessories I can see a tile with the battery status (in %)
I do not see this in the HomeApp.... to do so I have to long-press a tile eg the Party Mode Switch and then go to the settings (cog or scroll down)... then I see it in the status

I assume this is a limitation of the HomeApp? in Eve App I also don't see it... (same workaround... in fact even more complicated)

Many thanks

PS: great work!

**Comment by normen** [comment]
I can't do much about how HomeKit Apps display the battery percentage, sorry. You can always ask Siri about the battery state though, which I find is the easiest method.
