### ISSUE TITLE
Installation/ Setup

### ISSUE THREAD

**Issue by Bildhauer1963** [normen/homebridge-landroid#36]
Hello,

as a "newbie" I managed to install your software. Where do I find the config.json file to do the configuration or where must ist be placed?

Thanks in advance!

**Comment by normen** [comment]
This is a plugin for homebridge, you'll have to check out their documentation for that info. The file location depends on the system you run homebridge on (Raspberry Pi, Windows PC etc). Usually its in `{HOME}/.homebridge/config.json`.

**Comment by Bildhauer1963** [comment]
I'm trying to get it run on a Mac. Is it the same there?

**Comment by normen** [comment]
I suppose, I am personally only running homebridge on Raspberry Pi though, which I'd strongly recommend as the homebridge server has to run continuously to pick up HomeKit events.
