### ISSUE TITLE
Battery Status

### ISSUE THREAD

**Issue by mistertropi** [normen/homebridge-landroid#37]
hello Norman,

Unfortunately I have a problem with the plugin. the battery status is always at 0% when the Homebridge is started. so you can get the Mower Running. 

I always have to restart the Homebridge first.

I Hope you can help me!

Lg Stelle

**Comment by normen** [comment]
Can't reproduce. Any errors in the log? I don't quite get how you say that a) its always 0% when HB is started and b) you say when you restart homebridge it works?
