### ISSUE TITLE
Feature request: Alert States as separate devices

### ISSUE THREAD

**Issue by JangoBritt** [normen/homebridge-landroid#4]
Hi @normen. I was wondering if there is any traction for separating the "Issues" device into its constituent states so that they can be used in other automations, rather than just knowing that there's something wrong with the Landroid?

Rain Delay could be presented as a moisture sensor (eg. could be used as a condition to prevent an irrigation cycle)

Lifted could be presented as a Security device, that can be used to trigger lights, sirens, notifications, etc?

Outside Wire could be a presence/occupancy sensor

**Comment by normen** [comment]
Sure, a PR is welcome. Just keep an option to have all combined.

**Comment by JangoBritt** [comment]
I'm afraid I'm being quite cheeky with this request, because I've never used GitHub for development before.

I have experience with JavaScript, but not in Node.js, and not with GitHub. I could try, but not sure where to start. lol

**Comment by normen** [comment]
Well as I have no special interest in this feature you‘ll have to wait and see if it seems easy enough to add if/when I‘m diving into this code next time. ;)

Otherwise - as you see it‘s not exactly a massive code base and HomeKit development is quite fun in general :D

**Comment by JangoBritt** [comment]
Sure, I understand. 

I’m just having a look around on another plugin, to dip my toes in. 

I’ll have a go at this some point, and if I can get it working on a fork, will raise a pull request

**Comment by BobbySlope** [comment]
Hi @normen a separate Sensor that Triggers at Rain Delay would be awesome to trigger automations in Apple Home. If you can have a look at it this would be awesome!

**Comment by normen** [comment]
Actually I added a "Leak Sensor" to report rain but that message is a bit invasive. The code is still in there. A humidity sensor messes up Siris weather reporting. There isn't really any good device types to abuse here.

**Comment by BobbySlope** [comment]
just another contact sensor or occupancy sensor should work to trigger automations

**Comment by normen** [comment]
Yeah I get it. But its ugly.

**Comment by normen** [comment]
There, I added an optional leak sensor for rain in 0.7.3 when you add the `rainsensor` option to config.json. You might have to reload the mowers from the cloud to get the new sensor in HomeKit.

**Comment by BobbySlope** [comment]
yeah I know, we will add some new accessory types to display this correctly in hoobs :)
Especially for your plugin there will be an Lawnmover accessory

nice, can u push it to npm?

**Comment by normen** [comment]
It's on NPM, update your internet ;)

**Comment by BobbySlope** [comment]
amazing, I will check it out right now

**Comment by normen** [comment]
> amazing, I will check it out right now

Don't get tangled up in Hoobs' hacks ;)

**Comment by BobbySlope** [comment]
nice works! 
Naja wird schwierig sich in der eigenen software zu verheddern :P

**Comment by normen** [comment]
Meinste? Nach dem 1462ten Hack und 5 Jahre später... wäre ich mir nicht so sicher ;) Und so Kram für Noobs einfach zu machen ist kein dankbares Geschäft.. Aber trotzdem alles Gute, hoffen wir mal dass Apple das nicht alles zuviel wird mit den ganzen Images und Hack-Boxen und sie HomeKit dicht machen.
