### ISSUE TITLE
"Leak" Sensor

### ISSUE THREAD

**Issue by Bildhauer1963** [normen/homebridge-landroid#41]
Hello,

if the rain sensor detects rain the home.app shows an alarm as a "leak" sensor. Is it possible to change the implementation so that the home.app will not show this kind of alarm?

Best regards

Stephan O.

**Comment by normen** [comment]
Sure, you can turn the sensor off. Otherwise, you can choose for every sensor what kinds of alarms you get in the Home App, main settings panel.
