### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by TA2k** [normen/homebridge-landroid#44]
iobroker.worx v1.7 needs the command   await self.landroidCloud.login() for login
iobroker.worx v2.0 is not compatible

**Comment by normen** [comment]
Cool, thanks for the info. I don't seem to be able to decode the data coming in via the `mqtt` event anymore either though..

**Comment by Phoenix-DH** [comment]
Just saw that there was just released a new version.
Maybe this is working better for decoding.

Would be really great.
Thanks for your work.

**Comment by normen** [comment]
Yeah, its been rewritten though, that means its not compatible without changes to this plugin. It'll be a while until I can look into this.

**Comment by Phoenix-DH** [comment]
Understood.

would be great … thanks.

**Comment by TA2k** [comment]
@normen You can also contact Positec directly to receive javascript template code for login and data polling

**Comment by normen** [comment]
Right, sounds like the iobroker.worx project isn't too happy about me re-using the existing work. That means it will take even longer until I get to fix this.

Edit: Btw for anyone interested, iobroker can also provide HomeKit support through a plugin that basically wraps homebridge and exposes the iobroker setup automatically. Meaning by converting your home control setup to iobroker you can control your Landroid as well.

**Comment by Phoenix-DH** [comment]
I have absolutely no experience in programming stuff for homebridge.

I love to have the landroids in home for automation. But dont know how to support.

**Comment by TA2k** [comment]
You can reuse but the class approach of the adapter was to complex and too hard to maintenance. It is easier when copy past the main methods of the code or use the example methods from posited directly

**Comment by Phoenix-DH** [comment]
Are there any news or things we may can help with?

**Comment by normen** [comment]
No news, I just have to do it. I hope I get it done until the next spring mowing season 😅

**Comment by Phoenix-DH** [comment]
👍🏻

**Comment by Marksi73** [comment]
Tada :) 

Hi @normen , my mowing season started today ;)

Is there any chance you get the plugin working again in the next few weeks? I am willing to support with money for coffee or other little things you might need... just to have a status would be very nice - thanks.

**Comment by normen** [comment]
Aww, I thought the "tada" was for a PR with the working adapter 😝 Can't say but yeah, I am thinking about taking my mowers out again as well.

**Comment by normen** [comment]
I basically copied all the necessary files and made some minimal adaptations so it should be easy to keep in sync, please test. Thanks again TA2k!
