### ISSUE TITLE
0.9.8 lost mover in home after no sync

### ISSUE THREAD

**Issue by Phoenix-DH** [normen/homebridge-landroid#45]
Hey,

I just moved to the newest version.
With installation the Home App gets not updates … no mover state change etc.

I removed today the mover by setting the checkbox in the settings app.

Now he wont come back. Sure I unchecked again.

No further error.

—-

Going back to 0.9.7 brings 404 🤷🏼‍♂️

**Comment by normen** [comment]
See #43
