### ISSUE TITLE
Try to send a message but could not find the mower

### ISSUE THREAD

**Issue by ZantioIT-SBJ** [normen/homebridge-landroid#46]
Hi Normen,

i has been using homebridge for a while, and the landroid plugin has been working perfect. i have now switched to Hoobs, and i can't connect? The mower gets in my apple homekit, but it's not responding?

From the log inside Hoobs:

_0/5/2022, 5:33:22 PMLandroid _BridgeBridge is running on port 51836.
10/5/2022, 5:33:23 PMLandroid BridgeConfiguration change_
10/5/2022, 5:33:23 PMlandroidbridge stopping
10/5/2022, 5:33:28 PMLandroid Bridge starting
10/5/2022, 5:33:32 PMLandroid BridgeLoaded plugin 'homebridge-landroid'
10/5/2022, 5:33:32 PMLandroid BridgeLoading 1 platforms...
10/5/2022, 5:33:32 PMLandroid BridgeLandroidDidFinishLaunching
10/5/2022, 5:33:32 PMLandroid BridgeLandroidworx is selected
10/5/2022, 5:33:32 PMLandroid BridgeLandroidConnect to worx
10/5/2022, 5:33:32 PMLandroid BridgeBridge is running on port 51836.
10/5/2022, 5:33:33 PMLandroid BridgeLandroidLogin form loaded
10/5/2022, 5:33:34 PMLandroid BridgeLandroidReceived Code
10/5/2022, 5:33:35 PMLandroid BridgeLandroidConnected to worx server
10/5/2022, 5:33:36 PMLandroid BridgeLandroid1 Recieve User Devices
10/5/2022, 5:33:36 PMLandroid BridgeLandroidFound Landroid in Worx Cloud with name: Odinsvej22
10/5/2022, 5:33:36 PMLandroid BridgeLandroidAdding Landroid Odinsvej22 to HomeKit
10/5/2022, 5:33:36 PMLandroid BridgeERROR[Landroid Bridge 4EA8@Landroid Odinsvej22@@Battery Level] characteristic value expected valid finite number and received "undefined" (undefined)
10/5/2022, 5:33:36 PMLandroid BridgeLandroidLandroid Odinsvej22 charging status changed to undefined, battery level undefined
10/5/2022, 5:33:36 PMLandroid BridgeLandroidLandroid Odinsvej22 status changed to undefined (undefined), battery level undefined
10/5/2022, 5:33:36 PMLandroid BridgeLandroidLandroid Odinsvej22 error code changed to undefined (undefined), battery level undefined
10/5/2022, 5:33:53 PMLandroid BridgeERROR[Landroid Bridge 4EA8@Landroid Odinsvej22@@Battery Level] characteristic value expected valid finite number and received "undefined" (undefined)
10/5/2022, 5:34:28 PMLandroid BridgeLandroidSending to Landroid Odinsvej22: [{"cmd":1}] (20203019840900141473)
10/5/2022, 5:34:28 PMLandroid BridgeLandroidTry to send a message but could not find the mower
10/5/2022, 5:35:06 PMLandroid BridgeLandroidSending to Landroid Odinsvej22: [{"cmd":3}] (20203019840900141473)
10/5/2022, 5:35:06 PMLandroid BridgeLandroidTry to send a message but could not find the mower
10/5/2022, 5:37:57 PMLandroid BridgeLandroidSending to Landroid Odinsvej22: [{"cmd":1}] (20203019840900141473)
10/5/2022, 5:37:57 PMLandroid BridgeLandroidTry to send a message but could not find the mower
10/5/2022, 5:38:10 PMLandroid BridgeLandroidSending to Landroid Odinsvej22: [{"cmd":3}] (20203019840900141473)
10/5/2022, 5:38:10 PMLandroid BridgeLandroidTry to send a message but could not find the mower
10/5/2022, 5:39:46 PMLandroid BridgeLandroidSending to Landroid Odinsvej22: [{"cmd":1}] (20203019840900141473)
10/5/2022, 5:39:46 PMLandroid BridgeLandroidTry to send a message but could not find the mower
10/5/2022, 5:40:02 PMLandroid BridgeLandroidSending to Landroid Odinsvej22: [{"cmd":3}] (20203019840900141473)
10/5/2022, 5:40:02 PMLandroid BridgeLandroidTry to send a message but could not find the mower_

![image](https://user-images.githubusercontent.com/64948124/194103818-bf3aa829-5a8d-444c-8900-f13eadbab961.png)

email and password is correct.

**Comment by normen** [comment]
See #43 and #44 - it has nothing to do with HOOBS although for support inside HOOBS please consult the HOOBS team.
