### ISSUE TITLE
Tried to send message but cannot find mower

### ISSUE THREAD

**Issue by woodgieboodgie** [normen/homebridge-landroid#48]
Hi,

Homebridge 1.5.1, NodeJs 16.18.0.  Error received is:

[homebridge-landroid] Sending to Landroid M: [{"cmd":3}] (202230284001000171B2)
[homebridge-landroid] Try to send a message but could not find the mower

Config is as per instructions, and username/password are correct as they work from the app. Do i need to specify the mower name within the config.json file?

{
    "email": "m*******@gmail.com",
    "pwd": "******-******-******",
    "cloud": "worx",
    "rainsensor": true,
    "platform": "Landroid",
    "_bridge": {
        "username": "0E:E7:EE:**:**:**",
        "port": 42555
    }
}

**Comment by woodgieboodgie** [comment]
Do i need to specify the mower name as below and if so is "dev_name" to be set to zero.  My mowers name is M.

"landroids": [
        {
            "name": "M",
            "dev_name": "0"
        }
    ],

**Comment by Littlericket** [comment]
Please see https://github.com/normen/homebridge-landroid/issues/44#issuecomment-1302604660

@normen has not yet updated this plugin.
