### ISSUE TITLE
Issue-Sensor - ContactSensor vs. OccupancySensor

### ISSUE THREAD

**Issue by nicoh88** [normen/homebridge-landroid#5]
Hi Normen,

danke für deine tolle Arbeit.
Für die Error-Stati hast du einen `ContactSensor` verwendet, ich glaube, dass ein `OccupancySensor`, vom Wortlaut her, besser passen würde.

**ContactSensor:** Offen, Geschlossen _(Grün)_
**OccupancySensor:** Ausgelöst _(Rot)_

Würde ja ein PR machen, aber die Änderung dauert, für dich, keine 2 Minuten. 😅 
(https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/blob/master/index.js#L119)

![Bildschirmfoto 2019-05-23 um 09 03 01](https://user-images.githubusercontent.com/264264/58232658-6524da80-7d3a-11e9-8bc1-ad6f960aa0a3.jpg)

Gruß Nico

**Comment by normen** [comment]
Siehe #4

**Comment by nicoh88** [comment]
PR: https://github.com/normen/homebridge-landroid/pull/6

![IMG_6521](https://user-images.githubusercontent.com/264264/58245251-a6c27f00-7d54-11e9-8b3d-456649600c17.jpeg)
