### ISSUE TITLE
AxiosError: Request failed with status code 429

### ISSUE THREAD

**Issue by woodgieboodgie** [normen/homebridge-landroid#52]
Hi Normen,

Great work on this plugin.

Upgraded to v0.11.1 and can access mower via Landroid app (was previously locked out per Issue #51) but now back in. However Homekit reports the mower is still away from its charger (which it isnt) and I cant switch the mower on. Has the plugin lost the mower?

**Comment by normen** [comment]
Hard to say without any info but worx just had some server issues so I'll pit it to that.
