### ISSUE TITLE
Login fails even though credentials test succeeds

### ISSUE THREAD

**Issue by mhaeberli** [normen/homebridge-landroid#54]
credentials test at:

https://account.worxlandroid.com/login

worked.

but:

Landroid BridgeLoaded plugin 'homebridge-landroid'
6/11/2023, 1:00:00 PMLandroid BridgeLoading 1 platforms...
6/11/2023, 1:00:00 PMLandroid BridgeLandroidWARNING: No account configured, please set email and password of your Worx account in config.json!
6/11/2023, 1:00:00 PMLandroid BridgeBridge is running on port 51846.
6/11/2023, 1:00:58 PMLandroid BridgeConfiguration change
6/11/2023, 1:00:58 PMlandroidbridge stopping
6/11/2023, 1:01:03 PMLandroid Bridge starting
6/11/2023, 1:01:06 PMLandroid BridgeLoaded plugin 'homebridge-landroid'
6/11/2023, 1:01:06 PMLandroid BridgeLoading 1 platforms...
6/11/2023, 1:01:06 PMLandroid BridgeLandroidDidFinishLaunching
6/11/2023, 1:01:06 PMLandroid BridgeLandroidLogin to worx
6/11/2023, 1:01:06 PMLandroid BridgeBridge is running on port 51846.
6/11/2023, 1:01:07 PMLandroid BridgeLandroidAxiosError: Request failed with status code 400
6/11/2023, 1:01:07 PMLandroid BridgeLandroid{"error":"invalid_grant","error_description":"The user credentials were incorrect.","message":"The user credentials were incorrect."}

Please advise if / when you can.  Cloud type chosen was worx from : worx / cress / landxcape

**Comment by normen** [comment]
See this:

> 6/11/2023, 1:00:00 PMLandroid BridgeLandroidWARNING: No account configured, please set email and password of your 

Looks like you didn't set a user/password combo in the config.
