### ISSUE TITLE
Leak sensor

### ISSUE THREAD

**Issue by lawiltshire** [normen/homebridge-landroid#55]
Hello, 

All last year my leak sensor was working. Then there were some problems over winter where the Landroid connection didn’t work at all but that’s all been fixed now. But the only thing that doesn’t work is the leak sensor. The sensor shows up in my home app but when it rains it doesn’t show the alert in the home app or homebridge. When I open the Landroid app though it does show that it’s raining so it’s not a sensor issue as I first thought. 

Is anyone else having this issue?

Thanks

**Comment by normen** [comment]
Hm, I didn't check the rain sensor after the last changes, I'll have a look if I can see a reason for this..

**Comment by normen** [comment]
Should be fixed in v0.11.6

**Comment by lawiltshire** [comment]
Thanks so much
