### ISSUE TITLE
Leak sensor / rain sensor

### ISSUE THREAD

**Issue by lawiltshire** [normen/homebridge-landroid#56]
Hey, reported this as not working yesterday and you kindly did some work on it.

However it’s rained this morning and the sensor still not activating. I’ve reinstalled the plugin , removed from home, re added etc . But still not coming up.

**Comment by normen** [comment]
Okay, another attempt at fixing that is in 0.11.7 - btw you can just reply to existing issues instead of making new ones.

**Comment by lawiltshire** [comment]
Thank you, sorry didn’t know whether you would get the message on a closed issue. Thanks for letting me know On 30 Jun 2023, at 10:59, Normen Hansen ***@***.***> wrote:﻿
Closed #56 as completed.

**Comment by lawiltshire** [comment]
Sorry still doesn’t seem to be working

**Comment by normen** [comment]
I do see the rain sensor activating now on my end. Make sure you're actually logging into the cloud, repeated logins may trigger a login ban period. Maybe try opening the Landoid App to trigger an update if the homebridge plugin is connected.

**Comment by lawiltshire** [comment]
Odd tried everything and still not working for me. Can control the lawnmower no problem but any other sensor doesn’t seem to work. Even when it’s out of boundary that sensor doesn’t work for me either. Is it related to the model I have? But then again it used to work before so not sureThanks LukeOn 30 Jun 2023, at 12:33, Normen Hansen ***@***.***> wrote:﻿
I do see the rain sensor activating now on my end. Make sure you're actually logging into the cloud, repeated logins may trigger a login ban period. Maybe try opening the Landoid App to trigger an update if the homebridge plugin is connected.

**Comment by normen** [comment]
Please check if 0.11.9 fixed this.

**Comment by lawiltshire** [comment]
Hello,

No still not working my end .

I’ve attached a message that appeared on my log when I sprayed water on the sensor 
![IMG_4288](https://github.com/normen/homebridge-landroid/assets/76825097/d1086e42-9cf6-4e73-9d2b-e4a0b8b7ef40)

**Comment by normen** [comment]
Looks like the data your mower provides isn't really compatible. Thats not something I can change in this plugin as that code resides in the iobroker plugin part.

**Comment by lawiltshire** [comment]
That’s weird , worked fine last summer.  Thanks for having a go On 2 Jul 2023, at 10:10, Normen Hansen ***@***.***> wrote:﻿
Looks like the data your mower provides isn't really compatible. Thats not something I can change in this plugin as that code resides in the iobroker plugin part.

**Comment by normen** [comment]
> That’s weird , worked fine last summer.

Yeah, they changed a lot on the cloud side since then.
