### ISSUE TITLE
Connection avec ferrex

### ISSUE THREAD

**Issue by Johnmat777** [normen/homebridge-landroid#61]
Hello i have a ferrex smart mower, but i don’t connect to Landroid. It connects to smart mower app.

**Comment by normen** [comment]
So you're saying that when you configure the `cloud` parameter as `ferrex` the mower isn't recognized?

**Comment by Johnmat777** [comment]
Ferrex app has not cloud, the mower connect with Bluetooth.

**Comment by normen** [comment]
Then it won't work with this plugin.

**Comment by Johnmat777** [comment]
This plugin work with ferrex mower ?

**Comment by normen** [comment]
Yes, those that use the wifi based cloud connection.

**Comment by Johnmat777** [comment]
The mower has wifi but connect it to application use Bluetooth
