### ISSUE TITLE
Changed Worx logon-domain? Plugin function broken! 

### ISSUE THREAD

**Issue by wesker84** [normen/homebridge-landroid#63]
Hi, 

it seems that Worx made a change to API. In my case, the plugin won‘t connect anymore, as subdomain id.eu.worx.com does not seem to exist anymore at all. 
So, function of the whole plugin is currently broken, I guess it will affect all users. 

Full error message:
Error: getaddrinfo ENOTFOUND id.eu.worx.com

Thanks in advance for checking this issue.

**Comment by wesker84** [comment]
Hi again, 
I fixed with workaround: 
In **/var/lib/homebridge/node_modules/homebridge-landroid/CloudConnector.js**, I changed line: 
from
loginUrl: "https://id.eu.worx.com/", 
to
**loginUrl: "https://id.worx.com/",** 
After restarting Homebridge, the Plugin authenticated and worked again.

**Comment by TITOUAN44DCLS** [comment]
Hi, 

I have the same problem

As a beginner in homebridge. Could you explain us, how to make that kind of modification ? (I have homebridge directly installed on a Raspberry Pi 

Thanks a lot

**Comment by wesker84** [comment]
> Hi,
> 
> I have the same problem
> 
> As a beginner in homebridge. Could you explain us, how to make that kind of modification ? (I have homebridge directly installed on a Raspberry Pi
> 
> Thanks a lot

Hi, 

My workaround is not homebridge-specific. It's more like Linux-basics you should get familiar with, when using solutions like Homebridge. At some point, you will always have to do modifications like this, even when doing configuration changes on Linux operating system itself. 

At following link, you can find a good tutorial, how it works. 
As I don't know if you are using Raspberry Pi OS (with graphical desktop), or Raspberry Pi OS Lite (with command line only), I searched for tutorial showing a solution for both. 
I prefer using Nano (point II. of tutorial), as I'm running Ubuntu Server (can be compared with Raspberry Pi OS Lite). 
https://www.linuxfordevices.com/tutorials/linux/edit-config-files-in-linux

After you have changed the file _**/var/lib/homebridge/node_modules/homebridge-landroid/CloudConnector.js**_, it's necessary to restart Homebridge (our the whole Pi) 

Hope this will help

**Comment by normen** [comment]
Should be fixed in the latest update. It might be that the update takes a while as theres some binaries that aren't available for all raspberry pi versions.

**Comment by wesker84** [comment]
![2023-11-03_172407](https://github.com/normen/homebridge-landroid/assets/57398168/498c07e7-b8cd-4632-a33b-940919cb29a1)
Hi, 

After update, I see devices twice. Once with correct name, once with **"Landroid [object Object]"** (see screenshot attached)

Here also some strange messages from log: 

_[11/3/2023, 5:20:18 PM] [Landroid] Found Landroid in Worx Cloud with name: **[object Object]
[Landroid [object Object]@@Name] characteristic value expected string and received object
[11/3/2023, 5:20:18 PM] [Landroid] Adding Landroid [object Object] to HomeKit**
[11/3/2023, 5:20:18 PM] [Landroid] Start MQTT connection
**Warning: Signed custom authorizers with signature will not work without a token key name and token value. Your connection may be rejected/stalled on the IoT Core side due to this. Please set the token key name and token value to connect to a signed custom authorizer.**_

I guess the first has something to do with the doubled shown devices, the last one my come for another reason; have not ever seen it yet. 
I've already reinstalled whole plugin, no change. 

Thanks for your work on this plugin again.

**Comment by TITOUAN44DCLS** [comment]
Hi, I managed to fix it :) Using only the terminal to modify the json. Thanks ChatGPT 💪 and you Duclos TitouanLe 3 nov. 2023 à 17:30, lhari84 ***@***.***> a écrit :﻿
Hi,
After update, I see devices twice. Once with correct name, once with "Landroid [object Object]" (see screenshot attached)
Here also some strange messages from log:
[11/3/2023, 5:20:18 PM] [Landroid] Found Landroid in Worx Cloud with name: [object Object]
[Landroid [object Object]@@name] characteristic value expected string and received object
[11/3/2023, 5:20:18 PM] [Landroid] Adding Landroid [object Object] to HomeKit
[11/3/2023, 5:20:18 PM] [Landroid] Start MQTT connection
Warning: Signed custom authorizers with signature will not work without a token key name and token value. Your connection may be rejected/stalled on the IoT Core side due to this. Please set the token key name and token value to connect to a signed custom authorizer.
I guess the first has something to do with the doubled shown devices, the last one my come for another reason; have not ever seen it yet.
I've already reinstalled whole plugin, no change.
Thanks for your work on this plugin again.

**Comment by normen** [comment]
The empty mower issue should be fixed as well.

**Comment by wesker84** [comment]
Great, thanks for the fix! 

What's still left in logs is following message: 
**[11/3/2023, 11:45:05 PM] [Landroid] Start MQTT connection
Warning: Signed custom authorizers with signature will not work without a token key name and token value. Your connection may be rejected/stalled on the IoT Core side due to this. Please set the token key name and token value to connect to a signed custom authorizer.** 

It appears since today's update, but maybe it's just coincidence and Worx has changed something again this day too. 
Anyway, it seems the plugin still works (even I can't test it in real life, as my mower went to winter break yesterday), but I'm afraid this issue may break the connection in next mowing season, if not solved.

**Comment by normen** [comment]
token key name and token value means "username and password" so we should be good I think - unless they change something else until next summer, I'm about done keeping up with that nonsense..

**Comment by JangoBritt** [comment]
+1 for this solution, btw... worked great.
