### ISSUE TITLE
it was working so nicely.. fhem mqtt2 instructions unclear :(

### ISSUE THREAD

**Issue by woodgieboodgie** [normen/homebridge-landroid#66]
i got fhem working but thereafter i am stuck

**Comment by normen** [comment]
cool story

**Comment by woodgieboodgie** [comment]
I am happy to contribute financially if you are interested to get it going again.
I have tried what the last post said to do (on a clean install) but it still doesn’t work and yes the fhem instructions are difficult to follow.
Can I twist your arm to help?

On 20 Feb 2024, at 00:17, Normen Hansen ***@***.***> wrote:

﻿

cool story

**Comment by normen** [comment]
Nah but maybe somebody wants to fork this and take your money.

**Comment by woodgieboodgie** [comment]
comic genius. if only your code worked as well as the sense of humor.
