### ISSUE TITLE
After Update 0.6.0 Homebridge crashes

### ISSUE THREAD

**Issue by tobihoby** [normen/homebridge-landroid#9]
[Homebridge] [2/15/2020, 17:55:36] TypeError: Cannot read property 'log' of undefined
    at MqttClient.<anonymous> (/home/hoobs/.hoobs/node_modules/iobroker.landroid-s/lib/mqttCloud.js:199:22)
    at MqttClient.emit (events.js:210:5)
    at TLSSocket.handleTLSerrors (/home/hoobs/.hoobs/node_modules/mqtt/lib/connect/tls.js:26:18)
    at TLSSocket.emit (events.js:215:7)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by normen** [comment]
Mhm, I think its an upstream issue in the iobroker landroid lib, see here:
https://github.com/MeisterTR/ioBroker.landroid-s/issues/32

Maybe something changed or is down on the server side.

**Comment by tobihoby** [comment]
I uninstalled the plugin again and reinstalled it. Problem has only existed since the update to 0.6.0.
Here is the config:

{
            "platform": "Landroid",
            "landroids": [
                {
                    "name": "MyLandroid",
                    "landroids": [
                        1
                    ]
                }
            ],
            "email": "xxxxxxx@xxxxx.com",
            "pwd": "123456",
            "plugin_map": {
                "plugin_name": "homebridge-landroid"
            }


When I start the homebridge again, it runs again until after about 30-60 minutes the abort appears with the error above.

**Comment by normen** [comment]
Yeah, again, the bug is not in the code of this plugin. But that config.json looks messed up, guess thats from pasting without code quotes though.

**Comment by normen** [comment]
Here, I posted a patch to the developer, when that gets released, update the plugin again to update its libraries: https://github.com/MeisterTR/ioBroker.landroid-s/pull/33

**Comment by normen** [comment]
I changed the library to use iobroker.worx, as suggested by the iobroker-landroid-s developer, see this change: https://github.com/normen/homebridge-landroid/commit/8fee8d42bd798d21699f212e6685bbc58a4d013e

Please update to 0.6.1 and check if it works, my mower is currently still stowed away so I can't test it with an active mower.

**Comment by normen** [comment]
0.6.1 had a bug sending commands, 0.6.2 should fix that.

**Comment by tobihoby** [comment]
it runs perfekt now! thanks
